------------------------ QUERY 1 ------------------------
SELECT M.TITLE_MOVIE, COD_STORE TIENDA, QUANTITY
FROM INVENTORY
INNER JOIN MOVIE M on M.COD_MOVIE = INVENTORY.COD_MOVIE
WHERE M.TITLE_MOVIE = 'SUGAR WONKA';

------------------------ QUERY 2 ------------------------
SELECT US.FIRST_LAST_USER NOMBRE_APELLIDO,
       SUM(AMOUNT_PAY) PAGO_TOTAL
FROM RENT
INNER JOIN USER_STORE US on RENT.FK_IDCLIENT = US.CODE_USER
GROUP BY US.FIRST_LAST_USER
HAVING COUNT(FK_IDCLIENT) >= 40;

------------------------ QUERY 3 ------------------------
CREATE VIEW DAYS_LATE AS
SELECT FK_IDCLIENT, FK_IDMOVIE, TO_NUMBER(
    SUBSTR(
        (DELIVERY_DATE - RENT_DATE), 1, INSTR((DELIVERY_DATE - RENT_DATE), ' ')-1)
    ) AS DIAS_PASADOS
FROM RENT
WHERE TO_NUMBER(
    SUBSTR(
        (DELIVERY_DATE - RENT_DATE), 1, INSTR((DELIVERY_DATE - RENT_DATE), ' ')-1)
    ) > 0;

SELECT US.FIRST_LAST_USER, DIAS_PASADOS, M.TITLE_MOVIE FROM DAYS_LATE DL
INNER JOIN USER_STORE US ON DL.FK_IDCLIENT = US.CODE_USER
INNER JOIN MOVIE M ON DL.FK_IDMOVIE = M.COD_MOVIE;

------------------------ QUERY 4 ------------------------
SELECT FIRST_LAST_ACTOR
FROM ACTOR
WHERE SUBSTR(FIRST_LAST_ACTOR, INSTR(FIRST_LAST_ACTOR, ' ')+1) LIKE '%son%'
ORDER BY FIRST_LAST_ACTOR ASC;

------------------------ QUERY 6 ------------------------
SELECT FIRST_LAST_ACTOR, TITLE_MOVIE, RELEASE_YEAR FROM MOV_ACT
INNER JOIN ACTOR A2 on A2.COD_ACTOR = MOV_ACT.FK_COD_ACTOR
INNER JOIN MOVIE M on M.COD_MOVIE = MOV_ACT.FK_COD_MOV
WHERE M.DESC_MOVIE LIKE '%Crocodile%' AND M.DESC_MOVIE LIKE '%Shark%'
ORDER BY SUBSTR(FIRST_LAST_ACTOR, INSTR(FIRST_LAST_ACTOR, ' ')+1) ASC;