------------------------------------- ROL ------------------------------------------------
INSERT INTO ROLE (TYPE_ROLE) VALUES ('C');
INSERT INTO ROLE (TYPE_ROLE) VALUES ('W');

------------------------------------- PAIS ------------------------------------------------
INSERT INTO COUNTRY (NAME_COUNTRY)
SELECT DISTINCT PAIS_CLIENTE FROM TEMP
WHERE PAIS_CLIENTE != '-'
UNION
SELECT DISTINCT PAIS_TIENDA FROM TEMP
WHERE PAIS_CLIENTE != '-'
UNION
SELECT DISTINCT PAIS_EMPLEADO FROM TEMP
WHERE PAIS_CLIENTE != '-';

------------------------------------- CATEGORIA ------------------------------------------------
INSERT INTO CATEGORY(NAME_CATEGORY)
SELECT DISTINCT CATEGORIA_PELICULA FROM TEMP
WHERE CATEGORIA_PELICULA IS NOT NULL AND CATEGORIA_PELICULA != '-';

------------------------------------- ACTOR ------------------------------------------------
INSERT INTO ACTOR (FIRST_LAST_ACTOR)
SELECT DISTINCT ACTOR_PELICULA FROM TEMP
WHERE ACTOR_PELICULA != '-';

------------------------------------- LENGUAJE ------------------------------------------------
INSERT INTO LANGUAJE (LANGUAJE_MOVIE)
SELECT DISTINCT LENGUAJE_PELICULA
FROM TEMP
WHERE LENGUAJE_PELICULA != '-';

------------------------------------- CIUDAD ------------------------------------------------
CREATE VIEW VIEW_CITY AS
SELECT DISTINCT ( CASE WHEN CODIGO_POSTAL_CLIENTE = '-' THEN NULL ELSE CODIGO_POSTAL_CLIENTE END ) COD_POSTAL,
                CIUDAD_CLIENTE,
                COUNTRY.COD_COUNTRY
FROM TEMP
INNER JOIN COUNTRY
ON TEMP.PAIS_CLIENTE = COUNTRY.NAME_COUNTRY
UNION
SELECT DISTINCT ( CASE WHEN CODIGO_POSTAL_EMPLEADO = '-' THEN NULL ELSE CODIGO_POSTAL_EMPLEADO END ) COD_POSTAL,
                CIUDAD_EMPLEADO,
                COUNTRY.COD_COUNTRY
FROM TEMP
INNER JOIN COUNTRY
ON TEMP.PAIS_EMPLEADO = COUNTRY.NAME_COUNTRY
UNION
SELECT DISTINCT ( CASE WHEN CODIGO_POSTAL_TIENDA = '-' THEN NULL ELSE CODIGO_POSTAL_TIENDA END ) COD_POSTAL,
                CIUDAD_TIENDA,
                COUNTRY.COD_COUNTRY
FROM TEMP
INNER JOIN COUNTRY
ON TEMP.PAIS_TIENDA = COUNTRY.NAME_COUNTRY;

INSERT INTO CITY (COD_POSTAL, NAME_CITY, FK_IDCOUNTRY)
SELECT COD_POSTAL, CIUDAD_CLIENTE, COD_COUNTRY FROM VIEW_CITY;

------------------------------------- TIENDA ------------------------------------------------
INSERT INTO STORE (NAME_STORE, ADDRESS_STORE, FK_IDCITY)
SELECT DISTINCT NOMBRE_TIENDA, DIRECCION_TIENDA, CITY.COD_CITY
FROM TEMP
INNER JOIN CITY
ON TEMP.CIUDAD_TIENDA = CITY.NAME_CITY
WHERE NOMBRE_TIENDA != '-';

------------------------------------- USUARIO ------------------------------------------------
CREATE VIEW VIEW_USER AS
SELECT DISTINCT NOMBRE_CLIENTE AS FIRST_LAST, CORREO_CLIENTE AS EMAIL, CLIENTE_ACTIVO AS ISACTIVE,
       null AS USERNAME_EMPLOYEE, null AS PASSWORD_EMPLOYEE, FECHA_CREACION, DIRECCION_CLIENTE,
        'C' AS ROLE, STORE.COD_STORE AS TIENDA, CITY.COD_CITY CIUDAD, null STORE_MANAGER
FROM TEMP
INNER JOIN STORE ON TEMP.TIENDA_PREFERIDA = STORE.NAME_STORE
INNER JOIN CITY ON TEMP.CIUDAD_CLIENTE = CITY.NAME_CITY 
    AND TEMP.CODIGO_POSTAL_CLIENTE = CITY.COD_POSTAL
WHERE NOMBRE_CLIENTE != '-'
UNION
SELECT DISTINCT NOMBRE_EMPLEADO, CORREO_EMPLEADO, EMPLEADO_ACTIVO,
        USUARIO_EMPLEADO, CONTRASENA_EMPLEADO, null, DIRECCION_EMPLEADO, 'W', STORE.COD_STORE,
        CITY.COD_CITY, null
FROM TEMP
INNER JOIN STORE ON TEMP.TIENDA_EMPLEADO = STORE.NAME_STORE
INNER JOIN CITY ON TEMP.CIUDAD_EMPLEADO = CITY.NAME_CITY
WHERE NOMBRE_CLIENTE != '-';

INSERT INTO USER_STORE (FIRST_LAST_USER, EMAIL_USER, STATUS, USERNAME, PASSWORD,
                        REGISTER_DATE, ADDRESS, FK_IDROL, FK_IDSTORE, FK_IDCITY, FK_IDCHIEF)
SELECT FIRST_LAST, EMAIL, (CASE WHEN ISACTIVE = 'Si' THEN 1 ELSE 0 END) AS STATUS,
       USERNAME_EMPLOYEE, PASSWORD_EMPLOYEE,
       FECHA_CREACION, DIRECCION_CLIENTE, ROLE, TIENDA, CIUDAD, STORE_MANAGER
FROM VIEW_USER;

------------------------------------- PELICULA ------------------------------------------------
INSERT INTO MOVIE (TITLE_MOVIE, DESC_MOVIE, RELEASE_YEAR,
                   DURATION, CANT_MAX_DAYS, UNIT_COST, SURCHARGE_COST, CLASSIFICATION)
SELECT DISTINCT NOMBRE_PELICULA, DESCRIPCION_PELICULA, ANO_LANZAMIENTO, DURACION, DIAS_RENTA,
       COSTO_RENTA, COSTO_POR_DANO, CLASIFICACION
FROM TEMP
WHERE NOMBRE_PELICULA != '-';

------------------------------------- RENTA ------------------------------------------------
CREATE VIEW VIEW_RENT AS
SELECT DISTINCT FECHA_PAGO, FECHA_RENTA, FECHA_RETORNO, MONTO_A_PAGAR,
                USER_STORE.CODE_USER, (
                    SELECT CODE_USER FROM USER_STORE WHERE FK_IDROL = 'W'
                    AND TEMP.NOMBRE_EMPLEADO = USER_STORE.FIRST_LAST_USER
                ) AS EMPLEADO,
                MOVIE.COD_MOVIE
FROM TEMP
INNER JOIN USER_STORE ON TEMP.NOMBRE_CLIENTE = USER_STORE.FIRST_LAST_USER
    AND USER_STORE.FK_IDROL = 'C'
INNER JOIN MOVIE ON TEMP.NOMBRE_PELICULA = MOVIE.TITLE_MOVIE;

INSERT INTO RENT (PAY_DATE, RENT_DATE, DELIVERY_DATE,
                  AMOUNT_PAY, FK_IDCLIENT, FK_IDWORKER, FK_IDMOVIE)
SELECT FECHA_PAGO, FECHA_RENTA,
       (CASE WHEN FECHA_RETORNO = '-' THEN '01-01-2000' ELSE FECHA_RETORNO END) AS FECHA_RETORNO,
       MONTO_A_PAGAR, CODE_USER, EMPLEADO, COD_MOVIE
FROM VIEW_RENT;

------------------------------------- MOVIE_CATEGORY ------------------------------------------------
INSERT INTO MOV_CATEGORY (FK_COD_MOV, MOV_CATEGORY)
SELECT DISTINCT MOVIE.COD_MOVIE, CATEGORY.COD_CATEGORY
FROM TEMP
INNER JOIN MOVIE ON MOVIE.TITLE_MOVIE = TEMP.NOMBRE_PELICULA
INNER JOIN CATEGORY ON CATEGORY.NAME_CATEGORY = TEMP.CATEGORIA_PELICULA;

------------------------------------- MOVIE_LANGUAJE ------------------------------------------------
INSERT INTO MOV_LANG (FK_COD_MOV, FK_COD_LANGUAJE)
SELECT DISTINCT MOVIE.COD_MOVIE, LANGUAJE.COD_LANGUAJE
FROM TEMP
INNER JOIN MOVIE ON MOVIE.TITLE_MOVIE = TEMP.NOMBRE_PELICULA
INNER JOIN LANGUAJE ON LANGUAJE.LANGUAJE_MOVIE = TEMP.LENGUAJE_PELICULA;

------------------------------------- MOVIE_ACTOR ------------------------------------------------
INSERT INTO MOV_ACT (FK_COD_MOV, FK_COD_ACTOR)
SELECT DISTINCT MOVIE.COD_MOVIE, ACTOR.COD_ACTOR
FROM TEMP
INNER JOIN MOVIE ON MOVIE.TITLE_MOVIE = TEMP.NOMBRE_PELICULA
INNER JOIN ACTOR ON ACTOR.FIRST_LAST_ACTOR = TEMP.ACTOR_PELICULA;

------------------------------------- INVENTORY ------------------------------------------------
CREATE VIEW VIEW_INVENTORY AS
SELECT DISTINCT MOVIE.COD_MOVIE, NOMBRE_PELICULA, TIENDA_PELICULA, STORE.COD_STORE,
                COUNT(*) CANTIDAD
FROM TEMP
INNER JOIN MOVIE ON MOVIE.TITLE_MOVIE = NOMBRE_PELICULA
INNER JOIN STORE ON STORE.NAME_STORE = TIENDA_PELICULA
WHERE NOMBRE_PELICULA != '-' AND TIENDA_PELICULA != '-'
GROUP BY NOMBRE_PELICULA, MOVIE.COD_MOVIE, TIENDA_PELICULA, STORE.COD_STORE;

INSERT INTO INVENTORY (COD_STORE, COD_MOVIE, QUANTITY)
SELECT COD_STORE, COD_MOVIE, CANTIDAD
FROM VIEW_INVENTORY;
