INSERT ALL
    INTO ROLE (TYPE_ROLE) VALUES ('C')
    INTO ROLE (TYPE_ROLE) VALUES ('W')
SELECT 1 FROM DUAL;

INSERT INTO COUNTRY (NAME_COUNTRY)
SELECT DISTINCT PAIS_CLIENTE FROM TEMP
UNION
SELECT DISTINCT PAIS_TIENDA FROM TEMP
UNION
SELECT DISTINCT PAIS_EMPLEADO FROM TEMP;

INSERT INTO CATEGORY(NAME_CATEGORY)
SELECT DISTINCT CATEGORIA_PELICULA FROM TEMP
WHERE CATEGORIA_PELICULA IS NOT NULL;

INSERT INTO ACTOR (FIRST_LAST_ACTOR)
SELECT DISTINCT ACTOR_PELICULA FROM TEMP
WHERE ACTOR_PELICULA != '-';

INSERT INTO LANGUAJE (LANGUAJE_MOVIE)
SELECT DISTINCT LENGUAJE_PELICULA FROM TEMP;

INSERT INTO CITY (COD_POSTAL, NAME_CITY, FK_IDCOUNTRY)
SELECT DISTINCT CODIGO_POSTAL_CLIENTE, CIUDAD_CLIENTE, COUNTRY.COD_COUNTRY
FROM TEMP
INNER JOIN COUNTRY
ON TEMP.PAIS_CLIENTE = COUNTRY.NAME_COUNTRY
UNION
SELECT DISTINCT CODIGO_POSTAL_EMPLEADO, CIUDAD_EMPLEADO, COUNTRY.COD_COUNTRY
FROM TEMP
INNER JOIN COUNTRY
ON TEMP.PAIS_EMPLEADO = COUNTRY.NAME_COUNTRY
UNION
SELECT DISTINCT CODIGO_POSTAL_TIENDA, CIUDAD_TIENDA, COUNTRY.COD_COUNTRY
FROM TEMP
INNER JOIN COUNTRY
ON TEMP.PAIS_TIENDA = COUNTRY.NAME_COUNTRY;

INSERT INTO STORE (NAME_STORE, ADDRESS_STORE, FK_IDCITY)
SELECT DISTINCT NOMBRE_TIENDA, DIRECCION_TIENDA, CITY.COD_CITY
FROM TEMP
INNER JOIN CITY
ON TEMP.CIUDAD_TIENDA = CITY.NAME_CITY;

CREATE VIEW USER_TEMP AS
SELECT NOMBRE_CLIENTE AS FIRST_LAST, CORREO_CLIENTE AS EMAIL, CLIENTE_ACTIVO AS ISACTIVE,
       null AS USERNAME_EMPLOYEE, null AS PASSWORD_EMPLOYEE,
       FECHA_CREACION AS CREATION_DATE, DIRECCION_CLIENTE AS ADDRESS, 'C' AS ROLE,
       STORE.COD_STORE, CITY.COD_CITY, null AS COD_CHIEF
FROM TEMP
INNER JOIN STORE ON TEMP.TIENDA_PREFERIDA = STORE.NAME_STORE
INNER JOIN CITY ON TEMP.CIUDAD_CLIENTE = CITY.NAME_CITY
UNION
SELECT NOMBRE_EMPLEADO, CORREO_EMPLEADO, EMPLEADO_ACTIVO, USUARIO_EMPLEADO, CONTRASENA_EMPLEADO,
       null, DIRECCION_EMPLEADO, 'W', STORE.COD_STORE, CITY.COD_CITY, null
FROM TEMP
INNER JOIN STORE ON TEMP.TIENDA_EMPLEADO = STORE.NAME_STORE
INNER JOIN CITY on TEMP.CIUDAD_EMPLEADO = CITY.NAME_CITY;

INSERT INTO USER_STORE (FIRST_LAST, EMAIL_USER, STATUS, USERNAME, PASSWORD,
                        REGISTER_DATE, ADDRESS, FK_IDROL, FK_IDSTORE, FK_IDCITY)
SELECT FIRST_LAST, EMAIL, (CASE WHEN ISACTIVE = 'Si' THEN 1 ELSE 0 END) AS STATUS,
       USERNAME_EMPLOYEE, PASSWORD_EMPLOYEE,
       CREATION_DATE, ADDRESS, ROLE, COD_STORE, COD_CITY
FROM USER_TEMP;